#################################################
# Base setup for a Linux server
#################################################
---
- hosts: localenv
  become: yes

  #vars:
  #  - newtimezone: Europe/Lisbon
  
  roles:
    - users
    - base_packages
    - epel
    - ntp
