---
- name: Update cache on Debian based systems
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install nginx package
  package:
    name: nginx
    state: present

- name: Ensure NGINX is started and starts at boot
  service:
    name: nginx
    enabled: true
    state: started

- name: Deploy base homepage on RedHat
  copy:
    src: files/index.html
    dest: /usr/share/nginx/html/index.html 
  when: deploy_homepage | bool
        and ansible_os_family == 'RedHat'

- name: Deploy base homepage on Debian
  copy:
    src: files/index.html
    dest: /var/www/html/index.html 
  when: deploy_homepage | bool
        and ansible_os_family == 'Debian'

- name: Restart NGINX
  service:
    name: nginx
    state: restarted