---
- hosts: all
  become: true

  tasks:
    - name: Set authorized key for remote user
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"