---
- name: Update cache on Debian based systems
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install base packages on Debian based systems
  apt: name={{ sys_packages }} state=present
  when: ansible_os_family == 'Debian'
    
- name: Install base packages on RedHat based systems
  yum: name={{ sys_packages }} state=present
  when: ansible_os_family == 'RedHat'